### PR TITLE
Brothers Restoring accounts .  !!!! YEA YEA YEA Man

### PR DESCRIPTION
**Pull request by kevscoolprojects**
What's shaken, What's Happening Brothers!!! :)   Basit, Umar, and Asim 

- **! This week objectives;**  

Restoring accounts.   Githubs, google doc sheets, zoom rooms etc... .>>  !!!! YEA YEA YEA Mannnnnnnnnnnn!!  2.  

- Next when everyone has time we will start to do some UI updates [remaking of **_**Dakota Mobile**  1.  Few updates to the app's _**_look and feel_**__**  An app that we have already published in google play's store.  Current version status is 1.0.  

  _Working URL here._
(https://www.dakota.com/learning-center) store updates making it buttery smooth.   

Also if you can skim over and review our most [coveted and treasured projects](https://github.com/IMS-Studio) when you have the time. @asimimamabdullah @Basit-Hussain98 @MuhammadUmarFarooq786 

image

### CODE REVIEW

**Comment by kevscoolprojects** [comment]
@MuhammadUmarFarooq786 @Basit-Hussain98 @asimimamabdullah @devloverumar Hope all is well!!!!  Slow and steady on fun projects teams using Slack, Google workspace git or bit bucket, and zooom1!!  **Zoom Zoom**

_`"Zoom-Zoom" is Mazda's global marketing slogan and has been used by the company since 2000. The slogan is meant to evoke the feeling of excitement, energy, and driving pleasure that is associated with driving a Mazda vehicle`_ [aka Kevs Workspace](https://media3.giphy.com/media/3ov9jPghXAsbvLmcjm/giphy.gif?cid=ecf05e478myl58dphx88yg22h9v2snadv7pfpkk6ukwhfzas&ep=v1_gifs_search&rid=giphy.gif&ct=g) 
 

p.s cross our fingers for no **MS teams gigs lol ! Slack and Zoom !!**

**Comment by MuhammadUmarFarooq786** [comment]
Zoom zoom 😊

**Comment by kevscoolprojects** [comment]
@kevscoolprojects @Basit-Hussain98 @MuhammadUmarFarooq786  Review and approval needed.  Thanks.

**Comment by MuhammadUmarFarooq786** [comment]
Yes sure.

**Comment by Basit-Hussain98** [comment]
Hi kevin,

Yea sure my man

**Comment by asimimamabdullah** [comment]
Will be happy to do.

**Review by umar-umich — APPROVED** [review]
LGTM 🙂

**Comment by kevscoolprojects** [comment]
:)  **LGTM  u all remember lol 

Let's Get That Money ------:)  Looks Good To Me**   

remember **Man made Money---- Money don't make the man**    ---- English translation of Go with God! Praise Ali

**[Thank God for all things!](https://en.wikipedia.org/wiki/Alhamdulillah)**  

image

**Comment by kevscoolprojects** [comment]
@Basit-Hussain98 @MuhammadUmarFarooq786 @asimimamabdullah @devloverumar @kevscoolprojects

**Pull request merged**
